dependencies:
 - name: nginx-ingress
   version: 0.21.0
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: prometheus
   version: 8.1.2
   repository: https://kubernetes-charts.storage.googleapis.com
