nginx-ingress:
  controller:
    service:
      loadBalancerIP: "35.247.50.41"

prometheus:
  pushgateway:
    enabled: false
  alertmanager:
    enabled: false
  server:
    ingress:
      enabled: true
      hosts:
        - prometheus.alpha.skyportal.io
