apiVersion: ENC[AES256_GCM,data:N04=,iv:c/Z101hjdFtaxwPFmUBRNi4+YFnmApenZB27Ja/5/Bg=,tag:5I2WHbONfKZn29I8rzEd9A==,type:str]
kind: ENC[AES256_GCM,data:INNitJo5,iv:1RTyaSzuUo3NWfe6mWCvSxKWc5Cxx5JWXT68j/XJ+VA=,tag:4R3TZtWNW/dttPtZqGPwvA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hA7LNgyE,iv:SUIKzQEVepyVh5W0F4u5DsBa8A9KMy30SFiLzybNlgc=,tag:piYodlI9B0WGDczVoV5L7g==,type:str]
type: ENC[AES256_GCM,data:hUq6KF7K,iv:blF0ssWj/vTCeK3N7jwBxvIi+OCO4agZxcI1d9XKV2Y=,tag:3h7CkWkqBhA+qRFY0871SA==,type:str]
stringData:
    config.yaml: ENC[AES256_GCM,data:kZU7BzCgK8XUivDQiR77KHAheRK++YxByFE1cif3Ba/PZ9bHXpFXFDaNUGY+N6Weatdw+X1j5+cy41TiiQdh4kNoCSe+WZ12mbH8enYNlV+wsQRTy73vLBtL9Z+jVDYcb3aVPFU6OIYq4Pjilfk7Owwcl+C4MTUbVG9e1LYYG+DuSA3YbON5X127uOe9A5mmO/id2KVifBQNKbtgxNmbMNkVRtOpr0zUYF4OSix2PzIBhKGPfaZiUBXYv1J1lV7QDuwwHi0lIoMwXfzpj/Evoyxp2Hc03u+pjK4KA80LUJTdI2EVp+UuLDARy5L/NO2nlmGa1OfUQkl6hTS4ID7H8of04l2xrI8VvzSpse5VlCqN3+sNz6b+bAjQ04HuoYZWKWJXvax3Hx0Q2mVsPeevdy7Ys0iC50pudW55KDwQrbRKwzPxNk0c4wdjPCQegjD9U/SSvyORPzKRm512X1QWnG+GK3T295Y6V1C/zhB79Po=,iv:JpJRgcOzL/SNBPZsMDCHZrPkR85q+Mj+AjqtpPZ2tPM=,tag:wo0K7SAxUjRVgALIWDCSug==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/skyportal-206621/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2018-12-12T01:53:17Z'
        enc: CiQA8uverGmc3Tk+Hfcda+On72UWK+q1sMXKS4p19XdIIvPVjugSSQBBE/1iGFBd/SXjtrDWmNoGe1LdltVVCDxl7qO07uil+IVjWK+taKGkxH2waoQ5jkfrCXrdRQGRApa7ePONS1+ngAyY7U2LPu8=
    azure_kv: []
    lastmodified: '2018-12-12T01:53:18Z'
    mac: ENC[AES256_GCM,data:d3LksIIFC3OjR/pLN11ATsXrIywxiV3DMFTtSg8NEGm1knyFFwncujmGk2j+6P0w6jLValYwgVDDq9ZGFLLa0vjcn+ZWFTp1dXSY5+iH3+zfYJPPeJ8XDdM9q9rjPPAnYrTCxU7qLmV5rDUYNEUK+j8IfdNG4P0ldq2u6XCDSG8=,iv:njLvic0wLwnLpcx6rVLGnt3+z7xQjzfuhviHqYCqsj8=,tag:6R71uoUFZEbV5NpcfokCXw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.2.0
