apiVersion: ENC[AES256_GCM,data:lic=,iv:nJGlWIUnAr9A8JnapNxf44rkIY6DZAwFaV+NLmfdspU=,tag:J2TxTxGDCcJw79nH5eJ+yg==,type:str]
kind: ENC[AES256_GCM,data:4gG8R+H+,iv:S6y2cWGNmMW8uqsqtb/+AeYX2k7YJBPqfDQzD1/hu6M=,tag:oM0pa3NVq2FcvAmQq3VJqw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VPZx3Xue,iv:KMBGK3DiQ0fotNi6BG7nBbDfa02MS0ptAaGtrdjIxbg=,tag:m2fuskgJuBcuKV29E3Osrw==,type:str]
type: ENC[AES256_GCM,data:EMSwJ9l4,iv:emEeHOHC0etQQBitAQJ0dZWoUW8orBRd3RSZf2S6mk8=,tag:EDzSukJ0ZtTZmihbDHQ+dA==,type:str]
stringData:
    config.yaml: ENC[AES256_GCM,data:FAPOHmld7Nx+OvqkGzY/+9RN10kjLSSSZcTLIZHf5tRMSvfT21e0uNu+IMUF//9cA4lPvZRUsUeGtKDxPZMLzwcKV6vMkdrUoMUUwlyvqLLqcYJ4g9Q0Nw+6vN1xU+SVA5jokk6Tv247+/wWAYfi48gLpgfp6Oq0+7lZSpQ1amzRUffBwCGvrWtG5YNSv3BPerqLrx0UlZ7apkmipqv8Nl5fKPFZlMM8d1m5KV/FGyRiJeGQ5GVmSExeAKAOQ+r31AykEReouBJbadFtTikjVf3ymaBSK7OQoIvLC5/1poLGMhtRH4BbM2oNaABX6h2V7GO51tRdABlQmcM/9c7FSgHWO1+IOgspnmLgnfNhO8K97HBtcOpP4JDq5QqbaeFP+5XVFld8bQY5xzMAPFvqGuIwijZ6Gt8Vp2qgLGWZ3f63xF89sG+x/ZYY9H39b+O32n8dZ0SwyW3jSHZEtVs6yxPLXLtHJwJ9U4BDl0ricDpS6tDI4/aE0vrmSik7tBaqSW4vhNQT51b2erC36nwwKeIqcp/C,iv:gQJ6k6lRX9CAtrNvndscasZNqCB64BIRGyTdypCMzLE=,tag:xu7Yy/gBAdScjY+jGUAuBw==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/skyportal-206621/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2020-06-30T09:27:48Z'
        enc: CiQA8uverJtJGfoLIz76FAV9k0qA/W343Y69w/ZdUjzeMA3KcGYSSQBBE/1ir6he9PXUprXPxvHN2KKIYvGDbxy/zBIAclalLDkVMnX3C3c3xDlSPatsXw2jYyd/8XyJjP4rZmlAjnj+jG44stc6KSM=
    azure_kv: []
    lastmodified: '2020-06-30T09:27:49Z'
    mac: ENC[AES256_GCM,data:UalM+E/bBibsY0UGGSTfdFQ7GzFWetW9+JL8kaNsLJ8SHYeX4j9v8jF6JBvDhZi+PiFxQPIbGOeD6QhSTqh4vD9jqwS4q3lHJRIQexLK6lPQSAQ88ea87G+rY7K8rUf9+FB4+8M5o0o24NrmZcEUMX0J2xSo8qCW2GhQc2EccB8=,iv:J24zOEJsAFtb4NUZZR+mNCMSLm3F7j8K+d6orrf3Keo=,tag:YVDKnvxB39S0bvQi6d9vXA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
