apiVersion: ENC[AES256_GCM,data:sD8=,iv:BiSoW05SDVOdsR9fEiC3rfmt9/mvzjtbZRz9+8EqbGs=,tag:py7e6QZutq+5w8ZwclNqJg==,type:str]
kind: ENC[AES256_GCM,data:Wrw57pQL,iv:XseShdC21cSkyB3PzMUHNg4R4L4d/I9Du8LEG/OlYTc=,tag:2HNX+AqSiqst6EQBbjVlyw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JL6cTNBN,iv:TbztYuYMaLdIOQivHng2+qdrrEUODWg8fLBThD5BC24=,tag:HObc6UlDYUgXQb4QfOvPBQ==,type:str]
type: ENC[AES256_GCM,data:XbVNuN6Q,iv:oc2rBK+fTEzAew9JSqH4V600Tl29yJYEg1Cax0ZRBn0=,tag:iuZL5y2Vm1nAhyhvY6j4JQ==,type:str]
stringData:
    config.yaml: ENC[AES256_GCM,data:JD6B8t1Q0uc+1LbVHMk/LulgE4YwGDUvJS7LXGJdSWlF6paPIY1KCPkvmlZMAy9aMooIfAoswqNTDHXj3xIJf1qEBx649oYWz+r3+j9c0mtgxPmXstzw6rKcxqKKebRmJBGOaFqjpfoYNEy0lZmGH0PiVRqO71+SmKtfcYc2yqyzckCqHMML6O3mGDDUM2tbU7Z5VGyM4E5zJvj7xZzT9A6aYJ5v4xGiu1TvHiHBNAyFLsvRe+i9rILdhAdwpBWWF1yYGjRF8UK/q1JRlUMfJPdKgeeo5LSusCS46GZa7M79TkMm3b8L+tiHM4gj6BVMJe6vWnOqbXULJL+S2mlnjRTXSnlIvOURFJS8od+t417EzKwsgqk6fGzBU9Habwzx4hoPNmPebOjxJQ4HScdIz5O3L2qfw8wb206+JPk7Qv867BtTFhE8WDHuBeubCykYONvNY+WsMBCbBTCP+7aKb3N4oB3dw62NTijx/2F7ZoQwIlOGMjaQiF8rpDACNpb3S0RMPM4=,iv:NY1raL70OZ/QAxhmetjwzZQmWiIgxbuAlwpado3Sk/4=,tag:QGdiwsUm2EKSx7sdo0PqNA==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/skyportal-206621/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2020-04-17T17:18:23Z'
        enc: CiQA8uverEtTqumRYIHiadFY4wQXIgfZDbBoDonW6VKmml2mSewSSQBBE/1iuOpG62jNTBHwWLQxOrsKV+6bcaqo37BLTBYqKaY+wYJVLxzqzxdGuitOVVh9FYzyxGs1WRfDvft/jTKSW7POQpGfpzU=
    azure_kv: []
    lastmodified: '2020-04-17T17:18:24Z'
    mac: ENC[AES256_GCM,data:HpEzSh5trHZJT6l4QqfTW/5E3uxiYVjwAkqBLrYXHRsgf8vsO3d2dmarhvRWfbBcjNFXuYWUuRgyhslenKcft9N2R8o6Q5p6GQtZ+cmQ+FM/PbmM9Lic2pknVsaa4WcieAcrQmJMkssA5W+hA4bkysLJ8beBOmHc5FFOvrlLOUQ=,iv:s4vPiZL6zNvU7b+rhhyJ4G8hoH8AxAZHdydwmI9i1fU=,tag:RJOeZLgx378IXh7FSPnbCA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
