apiVersion: v1
kind: ConfigMap
metadata:
  name: skyportal-config
  namespace: default
data:
  config.yaml: |
    app:
      secret-key: abc01234
      factory: skyportal.app_server.make_app

    database:
      database: skyportal
      host: localhost
      port: 5432
      user: skyportal
      password: ""

    server:
      auth:
          debug_login: True
          google_oauth2_key:
          google_oauth2_secret:
