apiVersion: batch/v1
kind: Job
metadata:
  name: load-demo-data
spec:
  backoffLimit: 0 # number of retries before throwing error
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
      - name: config
        secret:
          secretName: config
          items:
            - key: config.yaml
              path: config.yaml
      containers:
        - name: skyportal-for-load-demo-data
          image: skyportal/web:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: config
            mountPath: /etc/skyportal/
            readOnly: true
          env:
          - name: PYTHONPATH
            value: "."
          - name: FLAGS
            value: "--config=/etc/skyportal/config.yaml"
          command:
            - bash
            - -c
            - >
              source /skyportal_env/bin/activate && make load_demo_data
