apiVersion: batch/v1
kind: Job
metadata:
  name: upload-ztf
spec:
  backoffLimit: 0 # number of retries before throwing error
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
      - name: config
        configMap:
          name: config
      containers:
        - name: skyportal-for-ztf-upload
          image: acrellin/skyportalweb:ztfdemo
          imagePullPolicy: Always
          volumeMounts:
          - name: config
            mountPath: /etc/skyportal/
            readOnly: true
          env:
          - name: PYTHONPATH
            value: "."
          - name: FLAGS
            value: "--config=/etc/skyportal/config.yaml"
          # HACK FIXME: The bash command overwrites
          # config.yaml.defaults.  This is not the way it's supposed
          # to work, but neither initial_setup nor ztf_upload_avro
          # support the flags that load_env require (it's argparse
          # needs to be modified to ignore unknown arguments)
          command:
            - bash
            - -c
            - >
              curl -o tools/ztf_upload_avro.py https://raw.githubusercontent.com/stefanv/skyportal/homepage_layout_new/tools/ztf_upload_avro.py &&
              source /skyportal_env/bin/activate &&
              export PYTHONPATH="." &&
              cp /etc/skyportal/config.yaml config.yaml.defaults &&
              echo "Not executing:" python ./skyportal/initial_setup.py --adminusername="testuser@cesium-ml.org" &&
              python ./tools/ztf_upload_avro.py --workers=1 sjvdwalt@gmail.com https://ztf.uw.edu/alerts/public/ztf_public_20180626.tar.gz
