apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
      version: v9.6
  replicas: 1
  template:
    metadata:
      labels:
        app: db
        version: v9.6
    spec:
      containers:
        - name: postgres
          image: postgres:9.6
          ports:
            - containerPort: 5432  # Default service port
          env:
          - name: POSTGRES_USER
            value: skyportal
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_DB
            value: skyportal
