apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-db.yaml
- deployment-external-dns.yaml
- deployment-web.yaml
- service-web.yaml
- service-db.yaml
- ingress.yaml
